'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

type Job = { id: string; company: string; role: string; location: string | null; work_type: string | null; status: string; salary_range: string | null; url: string | null; next_step: string | null; next_step_date: string | null }
const statuses = ['Saved', 'Applied', 'Interviewing', 'Offer', 'Rejected', 'Withdrawn']
const statusClass: Record<string, string> = { Saved: 'chip-blue', Applied: 'chip-purple', Interviewing: 'chip-orange', Offer: 'chip-green', Rejected: 'chip-red', Withdrawn: 'chip-gray' }
const starterApplications = [
  ['Northstar Health', 'Product Designer', 'Remote', 'Remote', 'Interviewing', '$110k – $135k'], ['Cedar Labs', 'Frontend Engineer', 'New York, NY', 'Hybrid', 'Applied', '$125k – $155k'], ['Atlas Finance', 'UX Researcher', 'Boston, MA', 'On-site', 'Saved', '$95k – $120k'], ['Mosaic Studio', 'Brand Strategist', 'Remote', 'Remote', 'Saved', '$85k – $105k'], ['Brightwell', 'Product Manager', 'Austin, TX', 'Hybrid', 'Applied', '$120k – $145k'], ['Kindred Systems', 'Content Designer', 'Chicago, IL', 'Hybrid', 'Interviewing', '$90k – $115k'], ['Harbor & Co.', 'Operations Lead', 'Seattle, WA', 'On-site', 'Rejected', '$80k – $100k'], ['Juniper Cloud', 'Growth Marketer', 'Remote', 'Remote', 'Saved', '$75k – $95k'], ['Lumen Medical', 'Service Designer', 'Philadelphia, PA', 'Hybrid', 'Applied', '$100k – $125k'], ['Oakline Ventures', 'Data Analyst', 'Denver, CO', 'Hybrid', 'Saved', '$88k – $112k'],
].map(([company, role, location, work_type, status, salary_range]) => ({ company, role, location, work_type, status, salary_range }))
const columns = 'id,company,role,location,work_type,status,salary_range,url,next_step,next_step_date'

export default function Dashboard() {
  const supabase = useMemo(() => createClient(), [])
  const router = useRouter()
  const [user, setUser] = useState<any>(null); const [jobs, setJobs] = useState<Job[]>([]); const [filter, setFilter] = useState('All'); const [query, setQuery] = useState(''); const [modal, setModal] = useState<'add' | 'edit' | 'delete' | null>(null); const [selected, setSelected] = useState<Job | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  useEffect(() => { supabase.auth.getUser().then(({ data }) => { if (!data.user) { router.replace('/login'); return }; setUser(data.user); loadJobs(data.user.id) }) }, [supabase])
  async function loadJobs(uid: string) { const { data, error } = await supabase.from('jobs').select(columns).eq('user_id', uid).order('updated_at', { ascending: false }); if (error) { setLoading(false); return }; const existing = new Set((data || []).map((j) => j.company)); const missing = starterApplications.filter((j) => !existing.has(j.company)); let result = data || []; if (missing.length) { const { data: seeded } = await supabase.from('jobs').insert(missing.map((j) => ({ ...j, user_id: uid }))).select(columns); if (seeded) result = [...seeded, ...result] }; setJobs(result); setLoading(false) }
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!user) return; setSaving(true); const f = new FormData(e.currentTarget); const values = { company: String(f.get('company')), role: String(f.get('role')), location: String(f.get('location') || ''), work_type: String(f.get('work_type')), status: String(f.get('status')), salary_range: String(f.get('salary_range') || ''), url: String(f.get('url') || '') }; if (selected) { const { data } = await supabase.from('jobs').update(values).eq('id', selected.id).select(columns).single(); if (data) setJobs((current) => current.map((j) => j.id === selected.id ? data : j)) } else { const { data } = await supabase.from('jobs').insert({ ...values, user_id: user.id }).select(columns).single(); if (data) setJobs((current) => [data, ...current]) }; setSaving(false); closeModal() }
  async function remove() { if (!selected) return; await supabase.from('jobs').delete().eq('id', selected.id); setJobs((current) => current.filter((j) => j.id !== selected.id)); closeModal() }
  function closeModal() { setModal(null); setSelected(null) }
  const filtered = jobs.filter((j) => (filter === 'All' || j.status === filter) && `${j.company} ${j.role} ${j.location || ''}`.toLowerCase().includes(query.toLowerCase()))
  const count = (s: string) => jobs.filter((j) => j.status === s).length
  if (loading) return <main className="loading-screen">Preparing your workspace…</main>
  return <main className="app-shell">
    <aside className="sidebar"><Link href="/" className="brand"><span className="brand-mark">JT</span><span>JobTrack</span></Link><div className="workspace-profile"><span className="avatar">{user?.email?.[0]?.toUpperCase()}</span><div><strong>My workspace</strong><small>{user?.email}</small></div></div><p className="side-label">WORKSPACE</p><nav><Link className="active" href="/dashboard"><span>▦</span>Overview</Link><Link href="/insights"><span>◒</span>Insights</Link></nav><div className="sidebar-tip"><span className="tip-icon">✦</span><div><strong>Search health</strong><small>{jobs.length ? 'Your pipeline is active' : 'Add your first role'}</small></div><div className="tip-progress"><i style={{ width: `${Math.min(jobs.length * 10, 100)}%` }} /></div></div><div className="side-bottom"><button className="text-btn" onClick={() => supabase.auth.signOut().then(() => router.replace('/'))}>Sign out <span>↗</span></button></div></aside>
    <section className="workspace"><header className="mobile-header"><Link href="/" className="brand"><span className="brand-mark">JT</span><span>JobTrack</span></Link><Link href="/insights" className="text-btn">Insights</Link></header><div className="workspace-inner">
      <div className="page-heading"><div><p className="eyebrow">PERSONAL COMMAND CENTER</p><h1>Good to see you, <em>again.</em></h1><p className="muted">One clear view of every opportunity and your next best move.</p></div><button className="primary-btn" onClick={() => setModal('add')}>+ New application</button></div>
      <div className="stats-grid"><div className="stat-card featured"><span>Total pipeline</span><strong>{jobs.length}</strong><small><b className="trend-up">↑ Active</b> opportunities tracked</small></div><div className="stat-card stat-blue"><span>Applications sent</span><strong>{count('Applied')}</strong><small>Keep the rhythm going</small></div><div className="stat-card stat-orange"><span>Interviews</span><strong>{count('Interviewing')}</strong><small>Conversations underway</small></div><div className="stat-card stat-green"><span>Offers</span><strong>{count('Offer')}</strong><small>Celebrate the wins</small></div></div>
      <div className="job-list"><div className="toolbar"><div><h2>Application tracker</h2><p className="muted">{filtered.length} of {jobs.length} opportunities</p></div><div className="toolbar-right"><div className="filter-pills">{['All', ...statuses].map((s) => <button key={s} className={filter === s ? 'selected' : ''} onClick={() => setFilter(s)}>{s}</button>)}</div><input className="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search roles…" aria-label="Search applications" /></div></div><div className="table-wrap"><div className="list-head"><span>COMPANY / ROLE</span><span>LOCATION</span><span>STATUS</span><span>NEXT STEP</span><span>ACTIONS</span></div>{filtered.map((job) => <div className="job-row" key={job.id}><div className="company-cell"><span className="company-logo">{job.company.slice(0, 1)}</span><div><strong>{job.company}</strong><small>{job.role}</small></div></div><div className="job-location">{job.location || '—'}<small>{job.work_type || 'Flexible'}</small></div><div><span className={`status-chip ${statusClass[job.status] || 'chip-gray'}`}>{job.status}</span></div><div className="job-next">{job.next_step || (job.status === 'Interviewing' ? 'Prepare interview' : 'Follow up')}<small>{job.salary_range || 'Salary not listed'}</small></div><div className="row-actions"><button onClick={() => { setSelected(job); setModal('edit') }}>Edit</button><button className="delete-action" onClick={() => { setSelected(job); setModal('delete') }}>Delete</button></div></div>)}</div></div>
    </div></section>
    {modal === 'delete' && <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && closeModal()}><div className="modal-card confirm-card"><span className="confirm-icon">!</span><h2>Delete this application?</h2><p className="muted">This will permanently remove {selected?.company} from your tracker.</p><div className="modal-actions"><button className="secondary-btn" onClick={closeModal}>Cancel</button><button className="danger-btn" onClick={remove}>Delete application</button></div></div></div>}
    {(modal === 'add' || modal === 'edit') && <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && closeModal()}><form className="modal-card" onSubmit={save}><div className="modal-header"><div><p className="eyebrow">{selected ? 'UPDATE ROLE' : 'NEW OPPORTUNITY'}</p><h2>{selected ? 'Edit application' : 'Add application'}</h2></div><button type="button" className="close-btn" onClick={closeModal}>×</button></div><div className="form-grid"><label>Company<input name="company" defaultValue={selected?.company || ''} required placeholder="e.g. Northstar Health" /></label><label>Role<input name="role" defaultValue={selected?.role || ''} required placeholder="e.g. Product Designer" /></label><label>Location<input name="location" defaultValue={selected?.location || ''} placeholder="Remote or city" /></label><label>Work type<select name="work_type" defaultValue={selected?.work_type || 'Remote'}><option>Remote</option><option>Hybrid</option><option>On-site</option></select></label><label>Status<select name="status" defaultValue={selected?.status || 'Saved'}>{statuses.map((s) => <option key={s}>{s}</option>)}</select></label><label>Salary range<input name="salary_range" defaultValue={selected?.salary_range || ''} placeholder="$90k – $120k" /></label><label className="full-field">Job link<input name="url" type="url" defaultValue={selected?.url || ''} placeholder="https://company.com/careers" /></label></div><div className="modal-actions"><button type="button" className="secondary-btn" onClick={closeModal}>Cancel</button><button className="primary-btn" disabled={saving}>{saving ? 'Saving…' : selected ? 'Save changes' : 'Add application'}</button></div></form></div>}
  </main>
}
Dashboard.displayName = 'Dashboard'
